import test from 'node:test';import assert from 'node:assert/strict';import {defaults,makeTrial,evaluate,walk,validData,parseImport,shouldAdvance,addVisible,gameIds,pathSolution} from '../dist/logic.js';import {MAX_LEVELS,STORIES} from '../dist/content.js';
const seed=()=>{let n=713;return()=>{n=(1664525*n+1013904223)>>>0;return n/4294967296;};};
const session=()=>({id:'session1',localDate:'2026-10-08',status:'playing',games:['memory','helper'],blockIndex:0,blockLimitMs:120000,blockVisibleMs:0,visibleMs:0,practiceDone:{},trialIndex:{},comfortBefore:{childChoice:'unsure',parentObservedSigns:[]},comfortAfter:{childChoice:'notAsked',parentObservedSigns:[]},breakUntil:null});
const trial=(n,extra={})=>({id:'t'+n,sessionId:'s1',gameId:'memory',level:1,completed:true,practice:false,correctFirst:true,supportTypes:[],invalidReason:null,localDate:n<5?'2026-10-07':'2026-10-08',...extra});
test('defaults use two-minute blocks and every supported game',()=>{assert.ok(validData(defaults()));assert.equal(Object.keys(defaults().settings.levels).length,8);assert.equal(defaults().settings.blockMs,120000);});
test('memory has 2/3/4 distinct locations and 1-location practice',()=>{const r=seed();for(let level=1;level<=3;level++)for(let i=0;i<100;i++){const t=makeTrial('memory',level,false,r,i);assert.equal(t.target.length,level+1);assert.equal(new Set(t.target).size,t.target.length);assert.equal(evaluate(t,t.target),true);assert.equal(evaluate(t,[]),false);}assert.equal(makeTrial('memory',3,true).target.length,1);});
test('helper target uses only visible objects and animals; ordered two-step instruction',()=>{for(let i=0;i<30;i++){const t=makeTrial('helper',2,false,seed(),i);assert.equal(t.target.length,2);for(const p of t.target){assert.ok(t.items.some(x=>x.id===p.item));assert.ok(t.animals.some(x=>x.id===p.animal));}assert.ok(evaluate(t,t.target));assert.equal(evaluate(t,[...t.target].reverse()),false);}});
test('all 12 stories can be reached, target is chronological at every level',()=>{assert.equal(new Set(Array.from({length:12},(_,i)=>makeTrial('story',2,false,seed(),i).story.id)).size,12);for(const level of [1,2,3]){const t=makeTrial('story',level);assert.equal(t.options.length,level===1?2:3);assert.ok(evaluate(t,t.target));assert.equal(evaluate(t,[...t.target].reverse()),false);}});
test('search has one match among 2/4/6 unique icons',()=>{for(const level of [1,2,3])for(let i=0;i<40;i++){const t=makeTrial('search',level,false,seed(),i);assert.equal(t.options.length,[2,4,6][level-1]);assert.equal(t.options.filter(x=>x.id===t.target).length,1);assert.equal(new Set(t.options.map(x=>x.id)).size,t.options.length);}});
test('stop sequence contains 7 go and 3 no-go; correct withholding is success',()=>{const ts=Array.from({length:10},(_,i)=>makeTrial('stop',1,false,seed(),i));assert.equal(ts.filter(t=>t.go).length,7);for(const t of ts){assert.ok(evaluate(t,t.go));assert.equal(evaluate(t,!t.go),false);}assert.notEqual(makeTrial('stop',1,true,seed(),0).go,makeTrial('stop',1,true,seed(),1).go);});
test('sorting changes announced rule after five trials; fixed levels keep rule',()=>{assert.equal(makeTrial('sort',3,false,seed(),4).rule,'color');assert.equal(makeTrial('sort',3,false,seed(),5).rule,'shape');assert.equal(makeTrial('sort',3,false,seed(),10).rule,'color');assert.equal(makeTrial('sort',1,false,seed(),9).rule,'color');assert.equal(makeTrial('sort',2).rule,'shape');});
test('paths accept both valid two-step routes and reject edge wrapping and obstacles',()=>{const t=makeTrial('path',1);assert.ok(evaluate(t,['up','right']));assert.ok(evaluate(t,['right','up']));assert.equal(walk(6,['left']).valid,false);assert.equal(walk(2,['right']).valid,false);assert.equal(evaluate(makeTrial('path',2),['right','up']),false);assert.ok(evaluate(makeTrial('path',3),['up','up','right']));assert.equal(evaluate(makeTrial('path',3),['up','right','up']),false);});
test('rhythm is parent observed, never an automated accuracy score',()=>{for(let l=1;l<=2;l++){const t=makeTrial('rhythm',l);assert.equal(t.target.length,l===1?2:3);assert.equal(evaluate(t,t.target),null);}});
test('level offer needs ten valid attempts over two dates, eight independent, <=1 supported',()=>{let ts=Array.from({length:10},(_,i)=>trial(i));assert.ok(shouldAdvance(ts,'memory',1));assert.equal(shouldAdvance(ts.slice(1),'memory',1),false);assert.equal(shouldAdvance(ts.map(t=>({...t,localDate:'2026-10-08'})),'memory',1),false);ts[0].supportTypes=['audioReplay'];ts[1].supportTypes=['visualCue'];assert.equal(shouldAdvance(ts,'memory',1),false);assert.equal(shouldAdvance(Array.from({length:10},(_,i)=>trial(i,{practice:true})),'memory',1),false);assert.equal(shouldAdvance(ts,'story',1),false);});
test('visible time freezes paused, caps block and survives serialization',()=>{let a=session();addVisible(a,130000);assert.equal(a.blockVisibleMs,120000);assert.equal(a.visibleMs,120000);a.status='paused';addVisible(a,60000);assert.equal(a.visibleMs,120000);a=JSON.parse(JSON.stringify(a));assert.equal(a.blockVisibleMs,120000);a.status='playing';a.blockIndex=1;a.blockVisibleMs=0;addVisible(a,130000);assert.equal(a.visibleMs,240000);});
test('import preserves unknown comfort and results but drops unfinished session',()=>{const d=defaults();d.active=session();d.trials=[trial(0)];assert.ok(validData(d));const parsed=parseImport(JSON.stringify(d));assert.equal(parsed.active,null);assert.equal(parsed.trials.length,1);assert.equal(d.active.comfortBefore.childChoice,'unsure');});
test('import rejects damaged records, unsafe states and unsupported schema',()=>{for(const mutate of [d=>d.schemaVersion=99,d=>d.settings.levels.helper=3,d=>d.sessions.push({id:'x',localDate:'2026-10-08',visibleMs:4}),d=>{d.active=session();delete d.active.practiceDone;},d=>{d.active=session();d.active.games=['memory','unknown'];},d=>{d.active=session();d.active.blockVisibleMs=120001;},d=>d.trials.push(trial(0,{supportTypes:['unknown']})),d=>d.observations.push({id:'x',localDate:'x',note:5})]){const d=defaults();mutate(d);assert.equal(validData(d),false);assert.throws(()=>parseImport(JSON.stringify(d)));}assert.throws(()=>parseImport('{'));});

test('all eight rotated/mirrored path templates are solvable at every level',()=>{for(let level=1;level<=3;level++)for(let i=0;i<8;i++){const t=makeTrial('path',level,false,seed(),i);const moves=pathSolution(t);assert.ok(moves.length>0);assert.ok(evaluate(t,moves));}});
